import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import TradingHorizonSettings from "./TradingHorizonSettings";
import { api } from "../../services/api";

vi.mock("../../services/api",()=>({api:{tradingProfile:vi.fn(),updateTradingProfile:vi.fn(),tradingHorizon:vi.fn()}}));
const profile={trading_profile:"auto_adaptive",strict_timeframe_unanimity:true,auto_profile_enabled:true,profile_revision:3,persistence_available:true};
const horizon={profile_label:"Mid-Term Trading",resolved_profile:"mid_term",execution_timeframe:"15m",confirmation_timeframes:["1h","4h"],structural_bias_timeframe:"1d",ready:false,direction:"NO_TRADE",estimated_holding_window:"1–5 days",explanation:"Why No Trade",agreement_matrix:[],blockers:["EXPECTED_EDGE_NOT_SUPPORTED"],strict_unanimity_required:true,unanimity_passed:false,expected_edge:null,current_edge:null,current_edge_supported:false,historical_edge_summary:{historical_expected_edge:-.0025,historical_edge_sample_count:12,authoritative:false,historical_performance:{resolved_sample_count:12,realized_return_mean:-.0025,realized_edge_lower_bound:-.01,realized_edge_upper_bound:.02,supported:true,reason:null},forecast_calibration:{forecast_count:12,forecast_expected_edge_mean:.04}},historical_data_available:true,historical_data_error_code:null,degraded:false,degraded_reasons:[],authority_status:"preview_blocked",persisted:false,previous_resolved_count:7,price_invalidation:{price:null},time_invalidation:{at:"2026-01-02T00:00:00Z"},previous_resolved_oos:{message:"Previous result"},profile_persistence_available:true,durable_idempotency_available:true,position_sizing:{configured_user_limit_usd:500,persisted_authority_limit_usd:400,risk_based_limit_usd:350,approved_risk_budget_usd:100}};

describe("TradingHorizonSettings",()=>{
 beforeEach(()=>{vi.clearAllMocks();(api.tradingProfile as ReturnType<typeof vi.fn>).mockResolvedValue(profile);(api.tradingHorizon as ReturnType<typeof vi.fn>).mockResolvedValue(horizon);(api.updateTradingProfile as ReturnType<typeof vi.fn>).mockResolvedValue({...profile,trading_profile:"mid_term",profile_revision:4})});
 it("loads server authority and saves with optimistic revision",async()=>{render(<TradingHorizonSettings/>);expect(await screen.findByText("Authoritative execution timeframe")).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText("Trading profile"),"mid_term");await userEvent.click(screen.getByRole("button",{name:"Save profile"}));expect(api.updateTradingProfile).toHaveBeenCalledWith(expect.objectContaining({trading_profile:"mid_term",expected_revision:3}));expect(await screen.findByRole("button",{name:"Saved"})).toBeDisabled();});
 it("shows a visible warning when persistence is unavailable",async()=>{(api.tradingProfile as ReturnType<typeof vi.fn>).mockRejectedValue(new Error("Profile store unavailable"));render(<TradingHorizonSettings/>);expect(await screen.findByText(/Execution safety unavailable/)).toBeInTheDocument();expect(screen.getByText(/Profile store unavailable/)).toBeInTheDocument();});
 it("labels realized OOS returns separately from forecast averages",async()=>{render(<TradingHorizonSettings/>);expect(await screen.findByText("preview_blocked")).toBeInTheDocument();expect(screen.getByText("NOT SUPPORTED")).toBeInTheDocument();expect(screen.getByText("Realized OOS average")).toBeInTheDocument();expect(screen.getByText("-0.25% · based on 12 resolved predictions")).toBeInTheDocument();expect(screen.getByText("Forecast average")).toBeInTheDocument();expect(screen.getByText("4.00%")).toBeInTheDocument();expect(screen.getByText("BLOCKED")).toBeInTheDocument();});
 it("renders a usable blocked state when history is degraded",async()=>{(api.tradingHorizon as ReturnType<typeof vi.fn>).mockResolvedValue({...horizon,degraded:true,historical_data_available:false,historical_data_error_code:"HISTORICAL_LEDGER_UNAVAILABLE",historical_edge_summary:{historical_expected_edge:null,historical_edge_sample_count:0,authoritative:false}});render(<TradingHorizonSettings/>);expect(await screen.findByText(/Historical performance unavailable/)).toBeInTheDocument();expect(screen.getByText("UNAVAILABLE")).toBeInTheDocument();expect(screen.getByText("BLOCKED")).toBeInTheDocument();});
 it("renders server-authored position sizing as read-only explanation",async()=>{render(<TradingHorizonSettings/>);expect(await screen.findByText("Position sizing")).toBeInTheDocument();expect(screen.getByText(/User limit: \$500/)).toHaveTextContent("Persisted authority ceiling: $400");expect(screen.getByText(/cannot increase them/)).toBeInTheDocument();});
});
