import { useCallback, useEffect, useState } from "react";
import { RefreshCcw } from "lucide-react";
import { api } from "../../services/api";

const PROFILES = [["auto_adaptive","Auto Adaptive"],["short_term","Short-Term Trading"],["mid_term","Mid-Term Trading"],["safe","Safe Trading"]] as const;
type AgreementRow={timeframe:string;direction:string;eligible:boolean;expected_edge:number|null;confidence:number|null};
type ProfileState={trading_profile:string;strict_timeframe_unanimity:boolean;auto_profile_enabled:boolean;profile_revision:number;persistence_available:boolean};
type HorizonResult={profile_label:string;resolved_profile:string;execution_timeframe:string;confirmation_timeframes:string[];structural_bias_timeframe:string;ready:boolean;direction:string;estimated_holding_window:string;explanation:string;agreement_matrix:AgreementRow[];blockers:string[];strict_unanimity_required:boolean;unanimity_passed:boolean;expected_edge:number|null;current_edge:number|null;current_edge_supported:boolean;historical_edge_summary:{historical_expected_edge:number|null;historical_edge_sample_count:number;authoritative:boolean;historical_performance?:{resolved_sample_count:number;realized_return_mean:number|null;realized_edge_lower_bound:number|null;realized_edge_upper_bound:number|null;supported:boolean;reason:string|null};forecast_calibration?:{forecast_count:number;forecast_expected_edge_mean:number|null}};historical_data_available:boolean;historical_data_error_code:string|null;degraded:boolean;degraded_reasons:{code:string;message:string}[];authority_status:"persisted_authority"|"preview_ready"|"preview_blocked"|"preview_informational";persisted:boolean;previous_resolved_count:number;price_invalidation:{price:number|null};time_invalidation:{at:string};previous_resolved_oos:{message:string};profile_persistence_available:boolean;durable_idempotency_available:boolean;bound_execution_decision?:{decision_id:string|null;timeframe:string|null};position_sizing?:{configured_user_limit_usd:number|null;persisted_authority_limit_usd:number|null;risk_based_limit_usd:number|null;approved_risk_budget_usd:number|null}};

export default function TradingHorizonSettings(){
 const [profile,setProfile]=useState(localStorage.getItem("quantx_trading_horizon_profile")||"auto_adaptive");
 const [serverProfile,setServerProfile]=useState<ProfileState|null>(null); const [symbol,setSymbol]=useState("BTCUSDT");
 const [result,setResult]=useState<HorizonResult|null>(null); const [state,setState]=useState<"loading"|"saved"|"dirty"|"saving"|"error">("loading"); const [error,setError]=useState("");
 const refresh=useCallback(async()=>{try{setResult(await api.tradingHorizon(symbol) as HorizonResult);}catch(exc){setError(exc instanceof Error?exc.message:"Trading Horizon unavailable");setState("error");}},[symbol]);
 useEffect(()=>{let live=true; void api.tradingProfile().then((value:ProfileState)=>{if(!live)return;setServerProfile(value);setProfile(value.trading_profile);localStorage.setItem("quantx_trading_horizon_profile",value.trading_profile);setState("saved");return refresh();}).catch((exc:unknown)=>{if(live){setError(exc instanceof Error?exc.message:"Profile persistence unavailable");setState("error");}});return()=>{live=false};},[refresh]);
 const save=async()=>{if(!serverProfile)return;setState("saving");setError("");try{const saved=await api.updateTradingProfile({trading_profile:profile,strict_timeframe_unanimity:true,auto_profile_enabled:profile==="auto_adaptive",expected_revision:serverProfile.profile_revision}) as ProfileState;setServerProfile(saved);localStorage.setItem("quantx_trading_horizon_profile",saved.trading_profile);setState("saved");await refresh();}catch(exc){setError(exc instanceof Error?exc.message:"Profile save failed");setState("error");}};
 return <div className="horizon-settings">
  <div className="horizon-controls"><label>Selected setting<select aria-label="Trading profile" value={profile} onChange={e=>{setProfile(e.target.value);setState("dirty")}}>{PROFILES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Symbol<select aria-label="Trading Horizon symbol" value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option><option>SOLUSDT</option></select></label><button onClick={save} disabled={!serverProfile||state==="saving"||state==="saved"}>{state==="saving"?"Saving…":state==="saved"?"Saved":"Save profile"}</button><button onClick={refresh}><RefreshCcw size={15}/> Refresh</button></div>
  <p className="regime-desc">Client state is never execution authority. Entries use only the authenticated server profile and its revision. Strict timeframe unanimity is required for automated entries.</p>
  {(state==="error"||result?.profile_persistence_available===false||result?.durable_idempotency_available===false)&&<div className="warning-box">Execution safety unavailable: {error||"profile persistence or durable idempotency is unavailable"}</div>}
  {result?.degraded&&<div className="warning-box">Historical performance unavailable. This preview is blocked and cannot authorize execution.</div>}
  {result&&<><div className="horizon-summary"><div><span>Profile setting</span><b>{PROFILES.find(([key])=>key===serverProfile?.trading_profile)?.[1]??"—"}</b></div><div><span>{serverProfile?.trading_profile==="auto_adaptive"?"Auto-selected profile":"Active profile"}</span><b>{result.profile_label}</b></div><div><span>Authoritative execution timeframe</span><b>{result.execution_timeframe}</b></div><div><span>Bound execution decision</span><b>{result.bound_execution_decision?.decision_id?`${result.bound_execution_decision.decision_id} · ${result.bound_execution_decision.timeframe}`:"—"}</b></div><div><span>Authority status</span><b>{result.authority_status}</b></div><div><span>Entry authority</span><b className={result.ready&&result.persisted&&!result.degraded?"green":"yellow"}>{result.ready&&result.persisted&&!result.degraded?"ELIGIBLE":"BLOCKED"}</b></div><div><span>Current predicted edge</span><b>{result.current_edge_supported&&result.current_edge!=null?`${(result.current_edge*100).toFixed(2)}%`:"NOT SUPPORTED"}</b></div><div><span>Realized OOS average</span><b>{!result.historical_data_available?"UNAVAILABLE":result.historical_edge_summary?.historical_performance?.realized_return_mean==null?"Insufficient resolved history":`${(result.historical_edge_summary.historical_performance.realized_return_mean*100).toFixed(2)}% · based on ${result.historical_edge_summary.historical_performance.resolved_sample_count} resolved predictions`}</b></div><div><span>Historical OOS lower bound</span><b>{result.historical_edge_summary?.historical_performance?.supported&&result.historical_edge_summary.historical_performance.realized_edge_lower_bound!=null?`${(result.historical_edge_summary.historical_performance.realized_edge_lower_bound*100).toFixed(2)}%`:"Insufficient resolved history"}</b></div><div><span>Forecast average</span><b>{result.historical_edge_summary?.forecast_calibration?.forecast_expected_edge_mean==null?"—":`${(result.historical_edge_summary.forecast_calibration.forecast_expected_edge_mean*100).toFixed(2)}%`}</b></div><div><span>Estimated hold</span><b>{result.estimated_holding_window}</b></div><div><span>Confirmation timeframes</span><b>{result.confirmation_timeframes.join(", ")}</b></div><div><span>Structural bias</span><b>{result.structural_bias_timeframe}</b></div><div><span>Strict unanimity required</span><b>{result.strict_unanimity_required?"YES":"NO"}</b></div><div><span>Unanimity passed</span><b>{result.unanimity_passed?"PASS":"FAIL"}</b></div><div><span>Resolved predictions</span><b>{result.previous_resolved_count}</b></div></div>
  <p className={result.ready?"horizon-why ready":"horizon-why blocked"}>{result.explanation}</p>
  {result.position_sizing&&<div className="horizon-why ready"><b>Position sizing</b><p>User limit: ${result.position_sizing.configured_user_limit_usd??"—"} · Persisted authority ceiling: ${result.position_sizing.persisted_authority_limit_usd??"—"} · Risk-based ceiling: ${result.position_sizing.risk_based_limit_usd??"—"}. Execution may reduce these limits but cannot increase them.</p></div>}
  <div className="horizon-matrix-wrap"><table className="horizon-matrix"><thead><tr><th>Timeframe</th><th>Direction</th><th>Confidence</th><th>Expected edge</th><th>Status</th></tr></thead><tbody>{result.agreement_matrix.map(row=><tr key={row.timeframe}><td>{row.timeframe}</td><td>{row.direction}</td><td>{row.confidence==null?"—":`${(row.confidence<=1?row.confidence*100:row.confidence).toFixed(1)}%`}</td><td>{row.expected_edge==null?"—":`${(row.expected_edge*100).toFixed(2)}%`}</td><td>{row.eligible?"Ready":"Blocked"}</td></tr>)}</tbody></table></div>
  {result.blockers.length>0&&<div><b>Exact blockers</b><ul>{result.blockers.map(item=><li key={item}>{item}</li>)}</ul></div>}
  <div className="horizon-invalidation"><span>Price invalidation: <b>{result.price_invalidation.price??"Awaiting entry/ATR"}</b></span><span>Time invalidation: <b>{new Date(result.time_invalidation.at).toLocaleString()}</b></span></div><p className="regime-desc">{result.previous_resolved_oos.message}</p></>}
 </div>;
}
